name = "Serinty"
description = "Home page site generator"
license = "MIT"
homepage = ""

min_version = "0.4.0"

demo = ""

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]
logo_path
navbar_items
# The theme author info: you!
[author]
name = "Andile Masela"
homepage = ""